name: ci/cd

on: [push]

jobs:
  test:
    name: "Lint & Test"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: python -m pip install ".[lint]"

    - name: Analyse the code with black
      run: black . --check --verbose --diff --color

    - name: Analyse types with mypy
      run: mypy quanty

    - name: Analyse imports with isort
      run: isort . --check --diff --color

    - name: Install dependencies
      run: python -m pip install ".[test]"

    - name: Run doctests
      run: python -m doctest -v quanty/base.py  quanty/basis.py

    - name: Run tests
      run: python -m unittest discover -v

    - name: Run examples
      run: for f in examples/*.py; do echo "\n$f" && python "$f"; done
